# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171228_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.CharField(max_length=50),
        ),
    ]
